# Generated by Django 5.2.7 on 2025-11-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etiqueta', models.CharField(max_length=100, verbose_name='Nombre de la etiqueta')),
                ('prompt_usado', models.TextField(verbose_name='Prompt usado')),
                ('datos_entrada', models.JSONField(help_text='JSON con los datos analizados', verbose_name='Datos de entrada')),
                ('resultado', models.TextField(verbose_name='Resultado del análisis')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Análisis de IA',
                'verbose_name_plural': 'Análisis de IA',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etiqueta', models.CharField(help_text='Identificador único para el template', max_length=100, unique=True, verbose_name='Nombre de la etiqueta')),
                ('prompt_template', models.TextField(help_text='Prompt con placeholders {variable}', verbose_name='Template del prompt')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del propósito del template', null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de Prompt',
                'verbose_name_plural': 'Templates de Prompts',
                'ordering': ['nombre_etiqueta'],
            },
        ),
    ]
