# Generated by Django 5.2.7 on 2025-12-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acta', '0002_acta_creado_por_acta_modificado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='estatus',
            field=models.BooleanField(default=False, help_text='Indica si el acta ha sido validada como correcta'),
        ),
    ]
