# Generated by Django 5.2.7 on 2025-12-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acta', '0003_acta_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='aprobado',
            field=models.BooleanField(default=False, help_text='Indica si el director de escuela lo aprobo'),
        ),
    ]
