# Generated by Django 5.2.7 on 2025-12-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acta', '0004_acta_aprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='aprobado',
            field=models.BooleanField(default=None, help_text='Indica si el director de escuela lo aprobó', null=True),
        ),
    ]
