# Generated by Django 5.2.7 on 2025-12-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='estatus',
            field=models.BooleanField(default=False, help_text='Indica si biblioteca ha sido validada como correcta'),
        ),
    ]
