# Generated by Django 5.2.7 on 2025-12-12 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acuerdo', '0002_acuerdo_estatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuerdo_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acuerdo_modificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
