# Generated by Django 5.2.7 on 2025-12-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_registrocalificado_snies'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocalificado',
            name='informe_final',
            field=models.JSONField(blank=True, default=dict, help_text='Diccionario con etiquetas dinamicas definidas por el usuario', verbose_name='Campos adicionales'),
        ),
        migrations.AddField(
            model_name='registrocalificado',
            name='numero_acta',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='acta'),
        ),
    ]
