# Generated by Django 5.2.7 on 2025-12-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_registrocalificado_informe_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocalificado',
            name='unificado',
            field=models.BooleanField(default=False, help_text='Indica si ya se realizo la unificacion', null=True),
        ),
    ]
