# Generated by Django 5.2.7 on 2025-12-17 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0005_registrocalificado_unificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyeccionTecnologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.BooleanField(default=False, help_text='Indica si proyeccion_tecnologica ha sido validada como correcta')),
                ('etiquetas_dinamicas', models.JSONField(blank=True, default=dict, help_text='Diccionario con etiquetas dinamicas definidas por el usuario', verbose_name='Campos adicionales')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyeccion_tecnologica_creadas', to=settings.AUTH_USER_MODEL)),
                ('llave_maestra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyeccion_tecnologica', to='Core.registrocalificado', to_field='llave_documento')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyeccion_tecnologica_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
