# Generated by Django 5.2.7 on 2025-10-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AspectosCurriculares', '0001_initial'),
        ('Core', '0002_alter_plantilladocumento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspectoscurriculares',
            name='llave_maestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aspectos_curriculares', to='Core.registrocalificado', to_field='llave_documento'),
        ),
    ]
